const en = {
    percentageHint: '100% is all selected publications in each year.', scaleMaximum: 'Shared vertical scale maximum', datedOnly: 'Only dated records are plotted.',
    copyLink: 'Copy view link', copied: 'Link copied', csv: 'Download CSV', svg: 'Download SVG', png: 'Download PNG',
    methodology: 'About these data', viewRecords: 'View publications', backFilters: 'Back to filters',
    analysis: 'Explore patterns', trends: 'Document types over time', count: 'Count', percentage: 'Percentage',
    authorsOverTime: 'Author publication timelines', authorHint: 'Choose authors in the search box to compare them. Otherwise the six most represented authors are shown. Select a year to see its publications.',
    collaborators: 'Shared publications', collaboratorHint: 'Choose an author to explore their collaborators. Each pair lists the publications recorded together.',
    families: 'Volumes and chapters', familyHint: 'Families containing a selected record, with all their recorded chapters for context. External references may not have their own entry in this register.',
    external: 'Referenced volume', show: 'Show', noResults: 'No results for this selection.', reset: 'Clear filters',
    scope: 'Rankings show alternatives: each excludes its own filter. The result list applies every filter.',
    publicationMethod: 'These are publications recorded by ZMO, not a complete measure of research output or employment. Names and venues are normalized conservatively. The latest year may be incomplete; historical coverage varies. Authorship includes recorded editorial roles.',
    networkLegend: 'Node size: publications in this scope. Line width: shared publications (capped for legibility). Select an author to focus their collaborators.',
    chartFailed: 'This chart is unavailable. The publication list and other views remain available.',
    missing: 'Missing metadata', undated: 'without a year', untyped: 'without a document type',
    cloud: 'Cloud', list: 'Frequency list', compare: 'Compare units', context: 'Source passages',
    term: 'Term', termSearch: 'Find a term', sort: 'Sort terms', frequent: 'Overall frequency', distinctive: 'Difference between units',
    comparisonHint: 'All three units are compared; the unit selector limits source passages only. Occurrences per 1,000 retained tokens; numbers in parentheses are raw counts. All terms are included in the source matrix. Differences describe these texts, not research effort.',
    contextHint: 'Select a term in the cloud, list, or comparison to read the original English passages. Inflected forms are matched through lemmatization.',
    cloudMethod: 'The corpus contains English research-unit descriptions and project texts, with stopwords removed and related word forms combined. Cloud size represents frequency with size limits. Colors are decorative. The occurrence total covers only displayed terms.',
    occurrences: 'occurrences', source: 'Source', corpus: 'retained tokens', projects: 'project entries',
    previousPage: 'Previous page', nextPage: 'Next page', ofTotal: 'of', loadError: 'The data could not be loaded.', retry: 'Try again',
    chooseTerm: 'Choose a term to read its source passages.', selected: 'Selected', year: 'Year', publications: 'Publications',
    view: 'View', exportError: 'Export failed. Please try again.', records: 'records', refresh: 'Last successful refresh',
};
const de = {
    percentageHint: '100 % sind alle ausgewählten Publikationen des jeweiligen Jahres.', scaleMaximum: 'Gemeinsamer Höchstwert der vertikalen Skala', datedOnly: 'Nur datierte Einträge werden dargestellt.',
    copyLink: 'Ansicht verlinken', copied: 'Link kopiert', csv: 'CSV herunterladen', svg: 'SVG herunterladen', png: 'PNG herunterladen',
    methodology: 'Über diese Daten', viewRecords: 'Publikationen anzeigen', backFilters: 'Zurück zu den Filtern',
    analysis: 'Muster erkunden', trends: 'Dokumenttypen im Zeitverlauf', count: 'Anzahl', percentage: 'Prozent',
    authorsOverTime: 'Publikationsverläufe der Autor*innen', authorHint: 'Autor*innen im Suchfeld auswählen und vergleichen. Sonst werden die sechs am häufigsten vertretenen Personen gezeigt. Ein Jahr auswählen, um die Publikationen zu sehen.',
    collaborators: 'Gemeinsame Publikationen', collaboratorHint: 'Eine Person auswählen, um ihre Koautor*innen zu erkunden. Jedes Paar zeigt die gemeinsam verzeichneten Publikationen.',
    families: 'Sammelbände und Beiträge', familyHint: 'Bände mit einem ausgewählten Eintrag und allen verzeichneten Beiträgen als Kontext. Externe Verweise haben möglicherweise keinen eigenen Registereintrag.',
    external: 'Referenzierter Band', show: 'Anzeigen', noResults: 'Keine Ergebnisse für diese Auswahl.', reset: 'Filter zurücksetzen',
    scope: 'Ranglisten zeigen Alternativen und berücksichtigen ihren eigenen Filter nicht. Die Ergebnisliste berücksichtigt alle Filter.',
    publicationMethod: 'Dies sind im ZMO-Register verzeichnete Publikationen, kein vollständiges Maß für Forschungsleistung oder Beschäftigungszeiten. Namen und Publikationsorte werden vorsichtig vereinheitlicht. Das jüngste Jahr kann unvollständig sein; die historische Abdeckung variiert. Autorschaft umfasst auch verzeichnete Herausgebertätigkeiten.',
    networkLegend: 'Knotengröße: Publikationen in dieser Auswahl. Linienbreite: gemeinsame Publikationen (zur besseren Lesbarkeit begrenzt). Eine Person auswählen, um ihr Umfeld zu sehen.',
    chartFailed: 'Dieses Diagramm ist nicht verfügbar. Die Publikationsliste und andere Ansichten bleiben zugänglich.',
    missing: 'Fehlende Metadaten', undated: 'ohne Jahr', untyped: 'ohne Dokumenttyp',
    cloud: 'Wortwolke', list: 'Häufigkeitsliste', compare: 'Einheiten vergleichen', context: 'Quelltexte',
    term: 'Begriff', termSearch: 'Begriff suchen', sort: 'Begriffe sortieren', frequent: 'Gesamthäufigkeit', distinctive: 'Unterschied zwischen Einheiten',
    comparisonHint: 'Verglichen werden alle drei Einheiten; die Einheitenwahl begrenzt nur die Quelltexte. Nennungen pro 1.000 berücksichtigte Wörter; in Klammern stehen die absoluten Zahlen. Die Datenmatrix enthält alle Begriffe. Unterschiede beschreiben diese Texte, nicht den Forschungsaufwand.',
    contextHint: 'Einen Begriff in der Wolke, Liste oder im Vergleich auswählen, um die englischen Quelltexte zu lesen. Wortformen werden durch Lemmatisierung zugeordnet.',
    cloudMethod: 'Das Korpus enthält englische Beschreibungen der Forschungseinheiten und Projekte. Stoppwörter werden entfernt und verwandte Wortformen zusammengeführt. Die Schriftgröße stellt die Häufigkeit innerhalb von Größenlimits dar. Farben sind dekorativ. Die Gesamtzahl der Nennungen umfasst nur die angezeigten Begriffe.',
    occurrences: 'Nennungen', source: 'Quelle', corpus: 'berücksichtigte Wörter', projects: 'Projekteinträge',
    previousPage: 'Vorherige Seite', nextPage: 'Nächste Seite', ofTotal: 'von', loadError: 'Die Daten konnten nicht geladen werden.', retry: 'Erneut versuchen',
    chooseTerm: 'Einen Begriff auswählen, um die Quelltexte zu lesen.', selected: 'Ausgewählt', year: 'Jahr', publications: 'Publikationen',
    view: 'Ansicht', exportError: 'Export fehlgeschlagen. Bitte erneut versuchen.', records: 'Einträge', refresh: 'Letzte erfolgreiche Aktualisierung',
};
export function exploreStrings(locale) { return locale === 'de' ? de : en; }
